services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: streamcart-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2182
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2182:2182"
    networks:
      - streamcart-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: streamcart-kafka
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2182
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - streamcart-network

  postgres:
    image: postgres:15
    container_name: streamcart-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - streamcart_postgres_data:/var/lib/postgresql/data
    networks:
      - streamcart-network

  airflow-webserver:
    image: apache/airflow:2.8.1
    container_name: streamcart-airflow-webserver
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@streamcart-postgres:5432/airflow_db
      AIRFLOW__CORE__FERNET_KEY: 'ZmDfcTF7_60GrrY167zsiPd67pEvs0aGOv2oasOM1Pg='
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    volumes:
      - ./orchestration/dags:/opt/airflow/dags
      - streamcart_airflow_logs:/opt/airflow/logs
    ports:
      - "8081:8080"
    command: webserver
    networks:
      - streamcart-network

  airflow-scheduler:
    image: apache/airflow:2.8.1
    container_name: streamcart-airflow-scheduler
    depends_on:
      - postgres
      - airflow-webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@streamcart-postgres:5432/airflow_db
      AIRFLOW__CORE__FERNET_KEY: 'ZmDfcTF7_60GrrY167zsiPd67pEvs0aGOv2oasOM1Pg='
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    volumes:
      - ./orchestration/dags:/opt/airflow/dags
      - streamcart_airflow_logs:/opt/airflow/logs
    command: scheduler
    networks:
      - streamcart-network

networks:
  streamcart-network:
    driver: bridge

volumes:
  streamcart_postgres_data:
  streamcart_airflow_logs:
